Place:
  kick: false
  message: You are not allowed to place this block.
  bannedBlocks:
   - 'BLOCK ID HERE'
Drop:
   kick: false
   message: You are not allowed to Drop this block.
   bannedBlocks:
   - 'BLOCK ID HERE'   
Break:
   kick: false
   message: You are not allowed to Break this block.
   bannedBlocks:
   - 'BLOCK ID HERE'  
Pickup:
   kick: false
   message: You are not allowed to pick up this block.
   bannedBlocks:
   - 'BLOCK ID HERE'     
   
