Place:
  kick: false
  message: You are not allowed to place this block.
  bannedBlocks:
   - 'BLOCK ID HERE'
Drop:
   kick: false
   message: You are not allowed to Drop this block.
   bannedBlocks:
   - 'BLOCK ID HERE'   
Break:
   kick: false
   message: You are not allowed to Break this block.
   bannedBlocks:
   - 'BLOCK ID HERE'  
Pickup:
   kick: false
   message: You are not allowed to pick up this block.
   bannedBlocks:
   - 'BLOCK ID HERE' 
SaplingReplant: true
SaplingBreak: true
CarrotReplant: true
PotatoReplant: true
WheatReplant: true
BlockBurn: true
LeavesDecay: true
Bucket:
  Water:
    kick: false
    message: You are not allowed to place water here.
  Lava:
    kick: false
    message: You are not allowed to place lava here.
Join:
  Message:
  Players:
    - 'Player Name Here'
Healingbed: false    
   
