name: BlockStopper
version: 3.0
main: me.baileypayne.blockstopper.BlockStopper
author: Bailey Payne
description: Totally Configurable Block Plugin
commands:
  blockstopper:
    description: Reloads the BlockStopper configuration file.
    usage: |
           /<command>
permissions:
  blockstopper.reload:
    description: access to reload
    default: op
