name: BlockStopper
version: 1.0
main: me.baileypayne.blockStopper.blockStopper
author: Bailey Payne
description: Disables players placing some blocks
commands:
  rblockstopper:
    description: Reloads the BlockStopper configuration file.
    usage: |
           /<command>
